services:
  farm:
    build: 
      context: ./backend/
    ports:
      - 8000:8000
    environment:
      - MONGO_ROOT_PASSWORD=password
    networks:
      - farm

  mongodb:
    image: mongo:latest
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - farm
  
networks:
  farm:

