TEAMS:
- test
- test3
- test4

FLAG_FORMAT': '[A-Z0-9]{31}='

# This configures how and where to submit flags.
# The protocol must be a module in protocols/ directory.
SYSTEM_TOKEN: '12ad1db9850dc371b36f9f105661f47c'
SYSTEM_PROTOCOL: 'ecsc24_http'
SYSTEM_URL: 'http://10.10.0.1:8080/flags'
SYSTEM_PORT: 8080

# SYSTEM_PROTOCOL: 'ructf_http'
# SYSTEM_URL: 'http://monitor.ructfe.org/flags'
# SYSTEM_TOKEN: 'your_secret_token'

# SYSTEM_PROTOCOL: 'volgactf'
# SYSTEM_HOST: '127.0.0.1'

# SYSTEM_PROTOCOL: 'forcad_tcp'
# SYSTEM_HOST: '127.0.0.1'
# SYSTEM_PORT: 31337
# TEAM_TOKEN: 'your_secret_token'

# The server will submit not more than SUBMIT_FLAG_LIMIT flags
# every SUBMIT_PERIOD seconds. Flags received more than
# FLAG_LIFETIME seconds ago will be skipped.
SUBMIT_FLAG_LIMIT: 50
SUBMIT_PERIOD: 5
FLAG_LIFETIME: 300

# Password for the web interface. You can use it with any login.
# This value will be excluded from the config before sending it to farm clients.
SERVER_PASSWORD: '1234'

# Use authorization for API requests
ENABLE_API_AUTH: True
API_TOKEN: ''